// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdzA02622-P24risizEwJt5m7wYTaYJXQ',
    appId: '1:335574407035:web:277d59cb0c3bfdb5140fde',
    messagingSenderId: '335574407035',
    projectId: 'tummybox-f2238',
    authDomain: 'tummybox-f2238.firebaseapp.com',
    storageBucket: 'tummybox-f2238.appspot.com',
    measurementId: 'G-CMNEXB7F2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2KcnPJ8d-A5mui2IQfYscKzS92BuyFx4',
    appId: '1:335574407035:android:f36f3029ee250153140fde',
    messagingSenderId: '335574407035',
    projectId: 'tummybox-f2238',
    storageBucket: 'tummybox-f2238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYpIq5ji4EbzcswCDRPBGYluKSHFD_b94',
    appId: '1:335574407035:ios:74446bdac8b8a932140fde',
    messagingSenderId: '335574407035',
    projectId: 'tummybox-f2238',
    storageBucket: 'tummybox-f2238.appspot.com',
    androidClientId: '335574407035-c1e9qeqa1c06maok0atip9rbes9fufu7.apps.googleusercontent.com',
    iosClientId: '335574407035-1n9fr3ehai6capikrl7cj4torkv7400l.apps.googleusercontent.com',
    iosBundleId: 'com.example.tbDeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYpIq5ji4EbzcswCDRPBGYluKSHFD_b94',
    appId: '1:335574407035:ios:0e68345d3a630f1a140fde',
    messagingSenderId: '335574407035',
    projectId: 'tummybox-f2238',
    storageBucket: 'tummybox-f2238.appspot.com',
    androidClientId: '335574407035-c1e9qeqa1c06maok0atip9rbes9fufu7.apps.googleusercontent.com',
    iosClientId: '335574407035-v6b7ql63ii38q8ca4hncuqtcck6c04a6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tbDeliveryapp.RunnerTests',
  );
}
